name: python-test

on: [push, pull_request]

jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    outputs:
      python-path: ${{ steps.set-python.outputs.python-path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        id: set-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Activate venv and run tests
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pytest

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    needs: test
    continue-on-error: true  # Prevents lint errors from breaking the pipeline
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pylint and run lint
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pylint
          pylint greeting/ || true  # Change 'greeting/' to your actual code directory

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Dummy build step
        run: echo "Build steps go here"
